### PR TITLE
Now it works in ECMASctipt5 strict mode

### PR DESCRIPTION
**Pull request by SpeCT**
Stop sharing private methods to global scope. Now retry-is is "use strict" mode compatible.

### CODE REVIEW

**Comment by SpeCT** [comment]
Found, that callback.js has it's own repo on github :(

**Comment by theozaurus** [comment]
Good catch, if you can do a pull request on callback-js I'll merge both of them.

**Comment by SpeCT** [comment]
Sure thing.

PS: Thanks for **retry-js**, awesome library :+1:

**Comment by theozaurus** [comment]
Glad you're finding it useful. Thanks for the pull request.

**Pull request merged**
